#!/usr/bin/env bash

# This script imports the data generated by `produce_overview_data.sh` to the
# AnICA UI.

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
BASE_DIR="$SCRIPT_DIR/../"

set -ex

$BASE_DIR/anica_ui/anica_ui/manage.py import_bbset \
    --isa x86 \
    "my custom BB set" \
    $BASE_DIR/results/new/overview_data.csv

